# Generated by Django 4.2.13 on 2024-07-05 12:30

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horse_name', models.CharField(max_length=200)),
                ('feeding_requirements', models.TextField()),
                ('exercise_requirements', models.TextField()),
                ('stay_start', models.DateField()),
                ('stay_end', models.DateField()),
                ('number_nights', models.IntegerField()),
                ('booked_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'unbooked'), (1, 'booked')], default=1)),
                ('bookingid', models.SlugField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['-booked_on'],
            },
        ),
        migrations.CreateModel(
            name='Stables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_num', models.IntegerField(default=10)),
                ('status', models.IntegerField(choices=[(0, 'unbooked'), (1, 'booked')], default=0)),
                ('cost_per_night', models.DecimalField(decimal_places=2, default=150, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Stable_availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('stable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingstablestays.stables')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('rating', models.IntegerField(default=0)),
                ('comment', models.TextField()),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('bookingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookingstablestays.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='cost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_costs', to='bookingstablestays.stables'),
        ),
        migrations.AddField(
            model_name='book',
            name='stable_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookingstablestays.stables'),
        ),
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
