# Generated by Django 4.2.13 on 2024-07-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingstablestays', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cost',
        ),
        migrations.AlterField(
            model_name='stables',
            name='stable_num',
            field=models.IntegerField(unique=True),
        ),
    ]
